name: VeloTV EPG Generator
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run Merge Script
        run: python merge.py

      - name: Compress and Finalize
        run: |
          gzip -9 -c epg.xml > epg.xml.gz
          ls -lh epg.xml.gz

      - name: Commit and Push
        run: |
          git config --global user.name "VeloTV-Bot"
          git config --global user.email "bot@velotv.app"
          git add epg.xml.gz
          git commit -m "Update EPG - Script Method" || echo "No changes"
          git push
