name: Daily XMLTV Merger

on:
  schedule:
    # 4 PM Eastern Time is 20:00 UTC
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml requests

      - name: Run xmlmerge
        env:
          CACHE_PATH: cache/
          OUTPUT_PATH: output/
        run: |
          mkdir -p cache output
          python xmlmerge.py

      - name: Upload merged EPG
        uses: actions/upload-artifact@v4
        with:
          name: merged-xmltv-epg
          path: output/merged.xml.gz
