name: Daily XMLTV Merger

on:
  schedule:
    # 4 PM Eastern Time is 20:00 UTC
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml requests

      - name: Run xmlmerge
        env:
          CACHE_PATH: cache/
          OUTPUT_PATH: output/
        run: |
          mkdir -p cache output
          python xmlmerge.py

      - name: Upload artifact (merged EPG)
        uses: actions/upload-artifact@v4
        with:
          name: merged-xmltv-epg
          path: output/merged.xml.gz

      - name: Configure Git for commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push merged EPG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add output/merged.xml.gz
          git commit -m "Update merged EPG [skip ci]" || echo "No changes to commit"
          git push
